config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :transactions
  resources :places
  resources :categories
  devise_for :users, skip: :registrations
  root "static_pages#home"

  get "/categories/:id/move_up", to: "categories#move_up", as: "categories_move_up"
  get "/categories/:id/move_down", to: "categories#move_down", as: "categories_move_down"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  acts_as_list
end

app/models/place.rb
# frozen_string_literal: true

class Place < ApplicationRecord
  belongs_to :category
  # Add default category if nothing selected like "NO CATEGORY title, NEED TO SET description"
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :place

  monetize :price_cents
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :move_up, :move_down]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:position).all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def move_up
    @category.move_higher

    redirect_to categories_path
  end

  def move_down
    @category.move_lower

    redirect_to categories_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description, :color, :position)
    end
end

app/controllers/places_controller.rb
# frozen_string_literal: true

class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all.order(:name)
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :category_id)
    end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  before_action :authenticate_user!

  def home
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:user_id, :place_id, :description, :price)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/places_helper.rb
# frozen_string_literal: true

module PlacesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% content_for :title, 'Categories'%>

<p id="notice"><%= notice %></p>

<h1 class="text-center">Categories</h1>

<br>

<%= button_to 'New Category', new_category_path, class: 'btn btn-primary' %>

<br><br>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Color</th>
        <th scope="col">Actions</th>
        <th scope="col">Position</th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each.with_index(1) do |category, index| %>
        <tr>
          <td scope="row"><b><%= index %></b></td>
          <td><%= category.title %></td>
          <td><%= category.description %></td>
          <td><%= category.color %></td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <%= button_to category, method: :get, class: 'btn btn-default btn-sm'  do %>
                <i class="fas fa-eye"></i>
              <% end %>
              <%= button_to edit_category_path(category), method: :get, class: 'btn btn-default btn-sm'  do %>
                <i class="fas fa-pen"></i>
              <% end %>
              <%= button_to category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm'  do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
          </td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <%= button_to categories_move_up_path(category), method: :get, class: 'btn btn-secondary btn-sm'  do %>
                <i class="fas fa-arrow-up"></i>
              <% end %>
              <%= button_to categories_move_down_path(category), method: :get, class: 'btn btn-secondary btn-sm'  do %>
                <i class="fas fa-arrow-down"></i>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<p>
  <strong>Position:</strong>
  <%= @category.position %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'LifAcc', root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if yield(:title) == 'Home' %>">
        <%= link_to 'Home', root_path, class: 'nav-link'%>
      </li>
      <li class="nav-item <%= 'active' if yield(:title) == 'Transactions' %>">
        <%= link_to 'Transactions', transactions_path, class: 'nav-link'%>
      </li>
      <li class="nav-item <%= 'active' if yield(:title) == 'Categories' %>">
        <%= link_to 'Categories', categories_path, class: 'nav-link'%>
      </li>
      <li class="nav-item <%= 'active' if yield(:title) == 'Places' %>">
        <%= link_to 'Places', places_path, class: 'nav-link'%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" disabled>Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LifAcc" %> - LifAcc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key == 'alert' ? 'warning' : 'info' %> alert-dismissible fade show" role="alert">
        <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <main role="main" class="container">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>

    <footer>
      <p class="text-center mt-5 mb-3 text-muted">&copy; 2020 LifAcc</p>
    </footer>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<% content_for :title, 'Places'%>

<p id="notice"><%= notice %></p>

<h1 class="text-center">Places</h1>

<br>

<%= button_to 'New Place', new_place_path, class: 'btn btn-primary' %>

<br><br>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Category</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @places.each.with_index(1) do |place, index| %>
        <tr>
          <td scope="row"><b><%= index %></b></td>
          <td><%= place.name %></td>
          <td><%= place.description %></td>
          <td><%= place&.category&.title %></td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <%= button_to place, method: :get, class: 'btn btn-default btn-sm'  do %>
                <i class="fas fa-eye"></i>
              <% end %>
              <%= button_to edit_place_path(place), method: :get, class: 'btn btn-default btn-sm'  do %>
                <i class="fas fa-pen"></i>
              <% end %>
              <%= button_to place, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm'  do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @place.category_id %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/static_pages/home.html.erb
<% content_for :title, 'Home'%>

<% content_for :content do %>
  <div data-controller="hello">
    <h1 data-target="hello.output"></h1>
  </div>
  <i class="fab fa-freebsd fa-3x mx-2"></i>
<% end %>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :place_id %>
    <%= form.text_field :place_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<% content_for :title, 'Transactions'%>

<p id="notice"><%= notice %></p>

<h1 class="text-center">Transactions</h1>

<br>

<%= button_to 'New Transaction', new_transaction_path, class: 'btn btn-primary' %>

<br><br>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">User</th>
        <th scope="col">Place</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @transactions.each.with_index(1) do |transaction, index| %>
        <tr>
          <td scope="row"><%= index %></td>
          <td><%= transaction.user_id %></td>
          <td><%= transaction.place_id %></td>
          <td><%= transaction.description %></td>
          <td><%= humanized_money_with_symbol transaction.price %></td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <%= button_to transaction, method: :get, class: 'btn btn-default btn-sm'  do %>
                <i class="fas fa-eye"></i>
              <% end %>
              <%= button_to edit_transaction_path(transaction), method: :get, class: 'btn btn-default btn-sm'  do %>
                <i class="fas fa-pen"></i>
              <% end %>
              <%= button_to transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm'  do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @transaction.user_id %>
</p>

<p>
  <strong>Place:</strong>
  <%= @transaction.place_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @transaction.price %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>